// Code generated by MockGen. DO NOT EDIT.
// Source: github_login.go
//
// Generated by this command:
//
//	mockgen -source=github_login.go -destination=../../../tests/handler/auth/mock_github_login.go -package=auth
//

// Package auth is a generated GoMock package.
package auth

import (
	context "context"
	reflect "reflect"

	domain "github.com/na2na-p/cargohold/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockGitHubOAuthUseCaseInterface is a mock of GitHubOAuthUseCaseInterface interface.
type MockGitHubOAuthUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGitHubOAuthUseCaseInterfaceMockRecorder
	isgomock struct{}
}

// MockGitHubOAuthUseCaseInterfaceMockRecorder is the mock recorder for MockGitHubOAuthUseCaseInterface.
type MockGitHubOAuthUseCaseInterfaceMockRecorder struct {
	mock *MockGitHubOAuthUseCaseInterface
}

// NewMockGitHubOAuthUseCaseInterface creates a new mock instance.
func NewMockGitHubOAuthUseCaseInterface(ctrl *gomock.Controller) *MockGitHubOAuthUseCaseInterface {
	mock := &MockGitHubOAuthUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockGitHubOAuthUseCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitHubOAuthUseCaseInterface) EXPECT() *MockGitHubOAuthUseCaseInterfaceMockRecorder {
	return m.recorder
}

// HandleCallback mocks base method.
func (m *MockGitHubOAuthUseCaseInterface) HandleCallback(ctx context.Context, code, state string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleCallback", ctx, code, state)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// HandleCallback indicates an expected call of HandleCallback.
func (mr *MockGitHubOAuthUseCaseInterfaceMockRecorder) HandleCallback(ctx, code, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCallback", reflect.TypeOf((*MockGitHubOAuthUseCaseInterface)(nil).HandleCallback), ctx, code, state)
}

// StartAuthentication mocks base method.
func (m *MockGitHubOAuthUseCaseInterface) StartAuthentication(ctx context.Context, repository *domain.RepositoryIdentifier, redirectURI string, shell string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartAuthentication", ctx, repository, redirectURI, shell)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartAuthentication indicates an expected call of StartAuthentication.
func (mr *MockGitHubOAuthUseCaseInterfaceMockRecorder) StartAuthentication(ctx, repository, redirectURI, shell any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartAuthentication", reflect.TypeOf((*MockGitHubOAuthUseCaseInterface)(nil).StartAuthentication), ctx, repository, redirectURI, shell)
}
