// Code generated by MockGen. DO NOT EDIT.
// Source: presign.go
//
// Generated by this command:
//
//	mockgen -source=presign.go -destination=../../../tests/infrastructure/s3/mock_presign.go -package=s3
//

// Package s3 is a generated GoMock package.
package s3

import (
	context "context"
	reflect "reflect"

	v4 "github.com/aws/aws-sdk-go-v2/aws/signer/v4"
	s3 "github.com/aws/aws-sdk-go-v2/service/s3"
	gomock "go.uber.org/mock/gomock"
)

// MockPresignClientInterface is a mock of PresignClientInterface interface.
type MockPresignClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPresignClientInterfaceMockRecorder
	isgomock struct{}
}

// MockPresignClientInterfaceMockRecorder is the mock recorder for MockPresignClientInterface.
type MockPresignClientInterfaceMockRecorder struct {
	mock *MockPresignClientInterface
}

// NewMockPresignClientInterface creates a new mock instance.
func NewMockPresignClientInterface(ctrl *gomock.Controller) *MockPresignClientInterface {
	mock := &MockPresignClientInterface{ctrl: ctrl}
	mock.recorder = &MockPresignClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPresignClientInterface) EXPECT() *MockPresignClientInterfaceMockRecorder {
	return m.recorder
}

// PresignGetObject mocks base method.
func (m *MockPresignClientInterface) PresignGetObject(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PresignGetObject", varargs...)
	ret0, _ := ret[0].(*v4.PresignedHTTPRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignGetObject indicates an expected call of PresignGetObject.
func (mr *MockPresignClientInterfaceMockRecorder) PresignGetObject(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignGetObject", reflect.TypeOf((*MockPresignClientInterface)(nil).PresignGetObject), varargs...)
}

// PresignPutObject mocks base method.
func (m *MockPresignClientInterface) PresignPutObject(ctx context.Context, params *s3.PutObjectInput, optFns ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PresignPutObject", varargs...)
	ret0, _ := ret[0].(*v4.PresignedHTTPRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignPutObject indicates an expected call of PresignPutObject.
func (mr *MockPresignClientInterfaceMockRecorder) PresignPutObject(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignPutObject", reflect.TypeOf((*MockPresignClientInterface)(nil).PresignPutObject), varargs...)
}
