FROM golang:1.27.1-alpine@sha256:8a5910f31396cd4d89662f56c68b3ae31d374308270a1c3bd96672ee5ed43414

WORKDIR /app

# git: Goモジュールのダウンロードに必要
# ca-certificates: HTTPS通信に必要
RUN apk add --no-cache git ca-certificates

COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD ["go", "test", "-v", "-tags=e2e", "./e2e/..."]
