FROM golang:1.27.1-alpine@sha256:cf6fca6641884b8433441b2b0652976f975e1d0fdd26d177eaaf8596087f3125

WORKDIR /app

# git: Goモジュールのダウンロードに必要
# ca-certificates: HTTPS通信に必要
RUN apk add --no-cache git ca-certificates

COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD ["go", "test", "-v", "-tags=e2e", "./e2e/..."]
