// Code generated by MockGen. DO NOT EDIT.
// Source: cache_repository.go
//
// Generated by this command:
//
//	mockgen -source=cache_repository.go -destination=../../tests/domain/mock_cache_repository.go -package=domain
//

// Package domain is a generated GoMock package.
package domain

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockCacheKeyGenerator is a mock of CacheKeyGenerator interface.
type MockCacheKeyGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockCacheKeyGeneratorMockRecorder
	isgomock struct{}
}

// MockCacheKeyGeneratorMockRecorder is the mock recorder for MockCacheKeyGenerator.
type MockCacheKeyGeneratorMockRecorder struct {
	mock *MockCacheKeyGenerator
}

// NewMockCacheKeyGenerator creates a new mock instance.
func NewMockCacheKeyGenerator(ctrl *gomock.Controller) *MockCacheKeyGenerator {
	mock := &MockCacheKeyGenerator{ctrl: ctrl}
	mock.recorder = &MockCacheKeyGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheKeyGenerator) EXPECT() *MockCacheKeyGeneratorMockRecorder {
	return m.recorder
}

// BatchUploadKey mocks base method.
func (m *MockCacheKeyGenerator) BatchUploadKey(oid string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUploadKey", oid)
	ret0, _ := ret[0].(string)
	return ret0
}

// BatchUploadKey indicates an expected call of BatchUploadKey.
func (mr *MockCacheKeyGeneratorMockRecorder) BatchUploadKey(oid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUploadKey", reflect.TypeOf((*MockCacheKeyGenerator)(nil).BatchUploadKey), oid)
}

// MetadataKey mocks base method.
func (m *MockCacheKeyGenerator) MetadataKey(oid string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MetadataKey", oid)
	ret0, _ := ret[0].(string)
	return ret0
}

// MetadataKey indicates an expected call of MetadataKey.
func (mr *MockCacheKeyGeneratorMockRecorder) MetadataKey(oid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MetadataKey", reflect.TypeOf((*MockCacheKeyGenerator)(nil).MetadataKey), oid)
}

// SessionKey mocks base method.
func (m *MockCacheKeyGenerator) SessionKey(sessionID string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionKey", sessionID)
	ret0, _ := ret[0].(string)
	return ret0
}

// SessionKey indicates an expected call of SessionKey.
func (mr *MockCacheKeyGeneratorMockRecorder) SessionKey(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionKey", reflect.TypeOf((*MockCacheKeyGenerator)(nil).SessionKey), sessionID)
}

// MockCacheConfig is a mock of CacheConfig interface.
type MockCacheConfig struct {
	ctrl     *gomock.Controller
	recorder *MockCacheConfigMockRecorder
	isgomock struct{}
}

// MockCacheConfigMockRecorder is the mock recorder for MockCacheConfig.
type MockCacheConfigMockRecorder struct {
	mock *MockCacheConfig
}

// NewMockCacheConfig creates a new mock instance.
func NewMockCacheConfig(ctrl *gomock.Controller) *MockCacheConfig {
	mock := &MockCacheConfig{ctrl: ctrl}
	mock.recorder = &MockCacheConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheConfig) EXPECT() *MockCacheConfigMockRecorder {
	return m.recorder
}

// MetadataTTL mocks base method.
func (m *MockCacheConfig) MetadataTTL() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MetadataTTL")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// MetadataTTL indicates an expected call of MetadataTTL.
func (mr *MockCacheConfigMockRecorder) MetadataTTL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MetadataTTL", reflect.TypeOf((*MockCacheConfig)(nil).MetadataTTL))
}

// MockCacheClient is a mock of CacheClient interface.
type MockCacheClient struct {
	ctrl     *gomock.Controller
	recorder *MockCacheClientMockRecorder
	isgomock struct{}
}

// MockCacheClientMockRecorder is the mock recorder for MockCacheClient.
type MockCacheClientMockRecorder struct {
	mock *MockCacheClient
}

// NewMockCacheClient creates a new mock instance.
func NewMockCacheClient(ctrl *gomock.Controller) *MockCacheClient {
	mock := &MockCacheClient{ctrl: ctrl}
	mock.recorder = &MockCacheClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheClient) EXPECT() *MockCacheClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockCacheClient) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCacheClientMockRecorder) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCacheClient)(nil).Delete), ctx, key)
}

// Exists mocks base method.
func (m *MockCacheClient) Exists(ctx context.Context, key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockCacheClientMockRecorder) Exists(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockCacheClient)(nil).Exists), ctx, key)
}

// GetJSON mocks base method.
func (m *MockCacheClient) GetJSON(ctx context.Context, key string, dest any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJSON", ctx, key, dest)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetJSON indicates an expected call of GetJSON.
func (mr *MockCacheClientMockRecorder) GetJSON(ctx, key, dest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJSON", reflect.TypeOf((*MockCacheClient)(nil).GetJSON), ctx, key, dest)
}

// Set mocks base method.
func (m *MockCacheClient) Set(ctx context.Context, key string, value any, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockCacheClientMockRecorder) Set(ctx, key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCacheClient)(nil).Set), ctx, key, value, ttl)
}

// SetJSON mocks base method.
func (m *MockCacheClient) SetJSON(ctx context.Context, key string, value any, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetJSON", ctx, key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetJSON indicates an expected call of SetJSON.
func (mr *MockCacheClientMockRecorder) SetJSON(ctx, key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetJSON", reflect.TypeOf((*MockCacheClient)(nil).SetJSON), ctx, key, value, ttl)
}
