// Code generated by MockGen. DO NOT EDIT.
// Source: repository_allowlist.go
//
// Generated by this command:
//
//	mockgen -source=repository_allowlist.go -destination=../../tests/domain/mock_repository_allowlist.go -package=domain
//

// Package domain is a generated GoMock package.
package domain

import (
	context "context"
	reflect "reflect"

	domain "github.com/na2na-p/cargohold/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRepositoryAllowlistRepository is a mock of RepositoryAllowlistRepository interface.
type MockRepositoryAllowlistRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryAllowlistRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryAllowlistRepositoryMockRecorder is the mock recorder for MockRepositoryAllowlistRepository.
type MockRepositoryAllowlistRepositoryMockRecorder struct {
	mock *MockRepositoryAllowlistRepository
}

// NewMockRepositoryAllowlistRepository creates a new mock instance.
func NewMockRepositoryAllowlistRepository(ctrl *gomock.Controller) *MockRepositoryAllowlistRepository {
	mock := &MockRepositoryAllowlistRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryAllowlistRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryAllowlistRepository) EXPECT() *MockRepositoryAllowlistRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockRepositoryAllowlistRepository) Add(ctx context.Context, repository *domain.AllowedRepository) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, repository)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockRepositoryAllowlistRepositoryMockRecorder) Add(ctx, repository any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockRepositoryAllowlistRepository)(nil).Add), ctx, repository)
}

// IsAllowed mocks base method.
func (m *MockRepositoryAllowlistRepository) IsAllowed(ctx context.Context, repository *domain.AllowedRepository) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAllowed", ctx, repository)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAllowed indicates an expected call of IsAllowed.
func (mr *MockRepositoryAllowlistRepositoryMockRecorder) IsAllowed(ctx, repository any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAllowed", reflect.TypeOf((*MockRepositoryAllowlistRepository)(nil).IsAllowed), ctx, repository)
}

// List mocks base method.
func (m *MockRepositoryAllowlistRepository) List(ctx context.Context) ([]*domain.AllowedRepository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*domain.AllowedRepository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepositoryAllowlistRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepositoryAllowlistRepository)(nil).List), ctx)
}

// Remove mocks base method.
func (m *MockRepositoryAllowlistRepository) Remove(ctx context.Context, repository *domain.AllowedRepository) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, repository)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockRepositoryAllowlistRepositoryMockRecorder) Remove(ctx, repository any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockRepositoryAllowlistRepository)(nil).Remove), ctx, repository)
}
