// Code generated by MockGen. DO NOT EDIT.
// Source: access_policy_repository.go
//
// Generated by this command:
//
//	mockgen -source=access_policy_repository.go -destination=../../tests/domain/mock_access_policy_repository.go -package=domain
//

// Package domain is a generated GoMock package.
package domain

import (
	context "context"
	reflect "reflect"

	domain "github.com/na2na-p/cargohold/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAccessPolicyRepository is a mock of AccessPolicyRepository interface.
type MockAccessPolicyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccessPolicyRepositoryMockRecorder
	isgomock struct{}
}

// MockAccessPolicyRepositoryMockRecorder is the mock recorder for MockAccessPolicyRepository.
type MockAccessPolicyRepositoryMockRecorder struct {
	mock *MockAccessPolicyRepository
}

// NewMockAccessPolicyRepository creates a new mock instance.
func NewMockAccessPolicyRepository(ctrl *gomock.Controller) *MockAccessPolicyRepository {
	mock := &MockAccessPolicyRepository{ctrl: ctrl}
	mock.recorder = &MockAccessPolicyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessPolicyRepository) EXPECT() *MockAccessPolicyRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockAccessPolicyRepository) Delete(ctx context.Context, oid domain.OID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, oid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAccessPolicyRepositoryMockRecorder) Delete(ctx, oid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAccessPolicyRepository)(nil).Delete), ctx, oid)
}

// FindByOID mocks base method.
func (m *MockAccessPolicyRepository) FindByOID(ctx context.Context, oid domain.OID) (*domain.AccessPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOID", ctx, oid)
	ret0, _ := ret[0].(*domain.AccessPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOID indicates an expected call of FindByOID.
func (mr *MockAccessPolicyRepositoryMockRecorder) FindByOID(ctx, oid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOID", reflect.TypeOf((*MockAccessPolicyRepository)(nil).FindByOID), ctx, oid)
}

// Save mocks base method.
func (m *MockAccessPolicyRepository) Save(ctx context.Context, policy *domain.AccessPolicy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, policy)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockAccessPolicyRepositoryMockRecorder) Save(ctx, policy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockAccessPolicyRepository)(nil).Save), ctx, policy)
}
