// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=../../tests/domain/mock_repository.go -package=domain
//

// Package domain is a generated GoMock package.
package domain

import (
	context "context"
	reflect "reflect"

	domain "github.com/na2na-p/cargohold/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockLFSObjectRepository is a mock of LFSObjectRepository interface.
type MockLFSObjectRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLFSObjectRepositoryMockRecorder
	isgomock struct{}
}

// MockLFSObjectRepositoryMockRecorder is the mock recorder for MockLFSObjectRepository.
type MockLFSObjectRepositoryMockRecorder struct {
	mock *MockLFSObjectRepository
}

// NewMockLFSObjectRepository creates a new mock instance.
func NewMockLFSObjectRepository(ctrl *gomock.Controller) *MockLFSObjectRepository {
	mock := &MockLFSObjectRepository{ctrl: ctrl}
	mock.recorder = &MockLFSObjectRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLFSObjectRepository) EXPECT() *MockLFSObjectRepositoryMockRecorder {
	return m.recorder
}

// ExistsByOID mocks base method.
func (m *MockLFSObjectRepository) ExistsByOID(ctx context.Context, oid domain.OID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByOID", ctx, oid)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByOID indicates an expected call of ExistsByOID.
func (mr *MockLFSObjectRepositoryMockRecorder) ExistsByOID(ctx, oid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByOID", reflect.TypeOf((*MockLFSObjectRepository)(nil).ExistsByOID), ctx, oid)
}

// FindByOID mocks base method.
func (m *MockLFSObjectRepository) FindByOID(ctx context.Context, oid domain.OID) (*domain.LFSObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOID", ctx, oid)
	ret0, _ := ret[0].(*domain.LFSObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOID indicates an expected call of FindByOID.
func (mr *MockLFSObjectRepositoryMockRecorder) FindByOID(ctx, oid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOID", reflect.TypeOf((*MockLFSObjectRepository)(nil).FindByOID), ctx, oid)
}

// Save mocks base method.
func (m *MockLFSObjectRepository) Save(ctx context.Context, obj *domain.LFSObject) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockLFSObjectRepositoryMockRecorder) Save(ctx, obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockLFSObjectRepository)(nil).Save), ctx, obj)
}

// Update mocks base method.
func (m *MockLFSObjectRepository) Update(ctx context.Context, obj *domain.LFSObject) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockLFSObjectRepositoryMockRecorder) Update(ctx, obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLFSObjectRepository)(nil).Update), ctx, obj)
}
