// Code generated by MockGen. DO NOT EDIT.
// Source: repository_allowlist_cache_client.go
//
// Generated by this command:
//
//	mockgen -source=repository_allowlist_cache_client.go -destination=../../tests/usecase/mock_repository_allowlist_cache_client.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRepositoryAllowlistCacheClient is a mock of RepositoryAllowlistCacheClient interface.
type MockRepositoryAllowlistCacheClient struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryAllowlistCacheClientMockRecorder
	isgomock struct{}
}

// MockRepositoryAllowlistCacheClientMockRecorder is the mock recorder for MockRepositoryAllowlistCacheClient.
type MockRepositoryAllowlistCacheClientMockRecorder struct {
	mock *MockRepositoryAllowlistCacheClient
}

// NewMockRepositoryAllowlistCacheClient creates a new mock instance.
func NewMockRepositoryAllowlistCacheClient(ctrl *gomock.Controller) *MockRepositoryAllowlistCacheClient {
	mock := &MockRepositoryAllowlistCacheClient{ctrl: ctrl}
	mock.recorder = &MockRepositoryAllowlistCacheClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryAllowlistCacheClient) EXPECT() *MockRepositoryAllowlistCacheClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockRepositoryAllowlistCacheClient) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryAllowlistCacheClientMockRecorder) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepositoryAllowlistCacheClient)(nil).Delete), ctx, key)
}

// Get mocks base method.
func (m *MockRepositoryAllowlistCacheClient) Get(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRepositoryAllowlistCacheClientMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepositoryAllowlistCacheClient)(nil).Get), ctx, key)
}

// Set mocks base method.
func (m *MockRepositoryAllowlistCacheClient) Set(ctx context.Context, key string, value any, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockRepositoryAllowlistCacheClientMockRecorder) Set(ctx, key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockRepositoryAllowlistCacheClient)(nil).Set), ctx, key, value, ttl)
}
