// Code generated by MockGen. DO NOT EDIT.
// Source: cache_key_manager.go
//
// Generated by this command:
//
//	mockgen -source=cache_key_manager.go -destination=../../tests/usecase/mock_cache_key_manager.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCacheKeyManager is a mock of CacheKeyManager interface.
type MockCacheKeyManager struct {
	ctrl     *gomock.Controller
	recorder *MockCacheKeyManagerMockRecorder
	isgomock struct{}
}

// MockCacheKeyManagerMockRecorder is the mock recorder for MockCacheKeyManager.
type MockCacheKeyManagerMockRecorder struct {
	mock *MockCacheKeyManager
}

// NewMockCacheKeyManager creates a new mock instance.
func NewMockCacheKeyManager(ctrl *gomock.Controller) *MockCacheKeyManager {
	mock := &MockCacheKeyManager{ctrl: ctrl}
	mock.recorder = &MockCacheKeyManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheKeyManager) EXPECT() *MockCacheKeyManagerMockRecorder {
	return m.recorder
}

// DeleteBatchUploadKey mocks base method.
func (m *MockCacheKeyManager) DeleteBatchUploadKey(ctx context.Context, oid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBatchUploadKey", ctx, oid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBatchUploadKey indicates an expected call of DeleteBatchUploadKey.
func (mr *MockCacheKeyManagerMockRecorder) DeleteBatchUploadKey(ctx, oid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBatchUploadKey", reflect.TypeOf((*MockCacheKeyManager)(nil).DeleteBatchUploadKey), ctx, oid)
}
