// Code generated by MockGen. DO NOT EDIT.
// Source: github_oidc_usecase.go
//
// Generated by this command:
//
//	mockgen -source=github_oidc_usecase.go -destination=../../tests/usecase/mock_github_oidc_usecase.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/na2na-p/cargohold/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockGitHubOIDCProvider is a mock of GitHubOIDCProvider interface.
type MockGitHubOIDCProvider struct {
	ctrl     *gomock.Controller
	recorder *MockGitHubOIDCProviderMockRecorder
	isgomock struct{}
}

// MockGitHubOIDCProviderMockRecorder is the mock recorder for MockGitHubOIDCProvider.
type MockGitHubOIDCProviderMockRecorder struct {
	mock *MockGitHubOIDCProvider
}

// NewMockGitHubOIDCProvider creates a new mock instance.
func NewMockGitHubOIDCProvider(ctrl *gomock.Controller) *MockGitHubOIDCProvider {
	mock := &MockGitHubOIDCProvider{ctrl: ctrl}
	mock.recorder = &MockGitHubOIDCProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitHubOIDCProvider) EXPECT() *MockGitHubOIDCProviderMockRecorder {
	return m.recorder
}

// VerifyIDToken mocks base method.
func (m *MockGitHubOIDCProvider) VerifyIDToken(ctx context.Context, token string) (*domain.GitHubUserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyIDToken", ctx, token)
	ret0, _ := ret[0].(*domain.GitHubUserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyIDToken indicates an expected call of VerifyIDToken.
func (mr *MockGitHubOIDCProviderMockRecorder) VerifyIDToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyIDToken", reflect.TypeOf((*MockGitHubOIDCProvider)(nil).VerifyIDToken), ctx, token)
}
