// Code generated by MockGen. DO NOT EDIT.
// Source: external_interfaces.go
//
// Generated by this command:
//
//	mockgen -source=external_interfaces.go -destination=../../tests/usecase/mock_external_interfaces.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	io "io"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockStorageKeyGenerator is a mock of StorageKeyGenerator interface.
type MockStorageKeyGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockStorageKeyGeneratorMockRecorder
	isgomock struct{}
}

// MockStorageKeyGeneratorMockRecorder is the mock recorder for MockStorageKeyGenerator.
type MockStorageKeyGeneratorMockRecorder struct {
	mock *MockStorageKeyGenerator
}

// NewMockStorageKeyGenerator creates a new mock instance.
func NewMockStorageKeyGenerator(ctrl *gomock.Controller) *MockStorageKeyGenerator {
	mock := &MockStorageKeyGenerator{ctrl: ctrl}
	mock.recorder = &MockStorageKeyGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageKeyGenerator) EXPECT() *MockStorageKeyGeneratorMockRecorder {
	return m.recorder
}

// GenerateStorageKey mocks base method.
func (m *MockStorageKeyGenerator) GenerateStorageKey(oid, hashAlgo string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateStorageKey", oid, hashAlgo)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateStorageKey indicates an expected call of GenerateStorageKey.
func (mr *MockStorageKeyGeneratorMockRecorder) GenerateStorageKey(oid, hashAlgo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateStorageKey", reflect.TypeOf((*MockStorageKeyGenerator)(nil).GenerateStorageKey), oid, hashAlgo)
}

// MockS3Client is a mock of S3Client interface.
type MockS3Client struct {
	ctrl     *gomock.Controller
	recorder *MockS3ClientMockRecorder
	isgomock struct{}
}

// MockS3ClientMockRecorder is the mock recorder for MockS3Client.
type MockS3ClientMockRecorder struct {
	mock *MockS3Client
}

// NewMockS3Client creates a new mock instance.
func NewMockS3Client(ctrl *gomock.Controller) *MockS3Client {
	mock := &MockS3Client{ctrl: ctrl}
	mock.recorder = &MockS3ClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3Client) EXPECT() *MockS3ClientMockRecorder {
	return m.recorder
}

// GenerateGetURL mocks base method.
func (m *MockS3Client) GenerateGetURL(ctx context.Context, key string, ttl time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateGetURL", ctx, key, ttl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateGetURL indicates an expected call of GenerateGetURL.
func (mr *MockS3ClientMockRecorder) GenerateGetURL(ctx, key, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateGetURL", reflect.TypeOf((*MockS3Client)(nil).GenerateGetURL), ctx, key, ttl)
}

// GeneratePutURL mocks base method.
func (m *MockS3Client) GeneratePutURL(ctx context.Context, key string, ttl time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePutURL", ctx, key, ttl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GeneratePutURL indicates an expected call of GeneratePutURL.
func (mr *MockS3ClientMockRecorder) GeneratePutURL(ctx, key, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePutURL", reflect.TypeOf((*MockS3Client)(nil).GeneratePutURL), ctx, key, ttl)
}

// MockObjectStorage is a mock of ObjectStorage interface.
type MockObjectStorage struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStorageMockRecorder
	isgomock struct{}
}

// MockObjectStorageMockRecorder is the mock recorder for MockObjectStorage.
type MockObjectStorageMockRecorder struct {
	mock *MockObjectStorage
}

// NewMockObjectStorage creates a new mock instance.
func NewMockObjectStorage(ctrl *gomock.Controller) *MockObjectStorage {
	mock := &MockObjectStorage{ctrl: ctrl}
	mock.recorder = &MockObjectStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStorage) EXPECT() *MockObjectStorageMockRecorder {
	return m.recorder
}

// GetObject mocks base method.
func (m *MockObjectStorage) GetObject(ctx context.Context, key string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject", ctx, key)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockObjectStorageMockRecorder) GetObject(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockObjectStorage)(nil).GetObject), ctx, key)
}

// PutObject mocks base method.
func (m *MockObjectStorage) PutObject(ctx context.Context, key string, body io.Reader, contentLength int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutObject", ctx, key, body, contentLength)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutObject indicates an expected call of PutObject.
func (mr *MockObjectStorageMockRecorder) PutObject(ctx, key, body, contentLength any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockObjectStorage)(nil).PutObject), ctx, key, body, contentLength)
}

// MockActionURLGenerator is a mock of ActionURLGenerator interface.
type MockActionURLGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockActionURLGeneratorMockRecorder
	isgomock struct{}
}

// MockActionURLGeneratorMockRecorder is the mock recorder for MockActionURLGenerator.
type MockActionURLGeneratorMockRecorder struct {
	mock *MockActionURLGenerator
}

// NewMockActionURLGenerator creates a new mock instance.
func NewMockActionURLGenerator(ctrl *gomock.Controller) *MockActionURLGenerator {
	mock := &MockActionURLGenerator{ctrl: ctrl}
	mock.recorder = &MockActionURLGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActionURLGenerator) EXPECT() *MockActionURLGeneratorMockRecorder {
	return m.recorder
}

// GenerateDownloadURL mocks base method.
func (m *MockActionURLGenerator) GenerateDownloadURL(baseURL, owner, repo, oid string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateDownloadURL", baseURL, owner, repo, oid)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateDownloadURL indicates an expected call of GenerateDownloadURL.
func (mr *MockActionURLGeneratorMockRecorder) GenerateDownloadURL(baseURL, owner, repo, oid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateDownloadURL", reflect.TypeOf((*MockActionURLGenerator)(nil).GenerateDownloadURL), baseURL, owner, repo, oid)
}

// GenerateUploadURL mocks base method.
func (m *MockActionURLGenerator) GenerateUploadURL(baseURL, owner, repo, oid string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateUploadURL", baseURL, owner, repo, oid)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateUploadURL indicates an expected call of GenerateUploadURL.
func (mr *MockActionURLGeneratorMockRecorder) GenerateUploadURL(baseURL, owner, repo, oid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateUploadURL", reflect.TypeOf((*MockActionURLGenerator)(nil).GenerateUploadURL), baseURL, owner, repo, oid)
}

// MockStorageErrorChecker is a mock of StorageErrorChecker interface.
type MockStorageErrorChecker struct {
	ctrl     *gomock.Controller
	recorder *MockStorageErrorCheckerMockRecorder
	isgomock struct{}
}

// MockStorageErrorCheckerMockRecorder is the mock recorder for MockStorageErrorChecker.
type MockStorageErrorCheckerMockRecorder struct {
	mock *MockStorageErrorChecker
}

// NewMockStorageErrorChecker creates a new mock instance.
func NewMockStorageErrorChecker(ctrl *gomock.Controller) *MockStorageErrorChecker {
	mock := &MockStorageErrorChecker{ctrl: ctrl}
	mock.recorder = &MockStorageErrorCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageErrorChecker) EXPECT() *MockStorageErrorCheckerMockRecorder {
	return m.recorder
}

// IsStorageError mocks base method.
func (m *MockStorageErrorChecker) IsStorageError(err error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsStorageError", err)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsStorageError indicates an expected call of IsStorageError.
func (mr *MockStorageErrorCheckerMockRecorder) IsStorageError(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsStorageError", reflect.TypeOf((*MockStorageErrorChecker)(nil).IsStorageError), err)
}
