// Code generated by MockGen. DO NOT EDIT.
// Source: upload_usecase.go
//
// Generated by this command:
//
//	mockgen -source=upload_usecase.go -destination=../../tests/usecase/mock_upload_usecase.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/na2na-p/cargohold/internal/domain"
	usecase "github.com/na2na-p/cargohold/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockUploadUseCase is a mock of UploadUseCase interface.
type MockUploadUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUploadUseCaseMockRecorder
	isgomock struct{}
}

// MockUploadUseCaseMockRecorder is the mock recorder for MockUploadUseCase.
type MockUploadUseCaseMockRecorder struct {
	mock *MockUploadUseCase
}

// NewMockUploadUseCase creates a new mock instance.
func NewMockUploadUseCase(ctrl *gomock.Controller) *MockUploadUseCase {
	mock := &MockUploadUseCase{ctrl: ctrl}
	mock.recorder = &MockUploadUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploadUseCase) EXPECT() *MockUploadUseCaseMockRecorder {
	return m.recorder
}

// HandleUploadObject mocks base method.
func (m *MockUploadUseCase) HandleUploadObject(ctx context.Context, baseURL, owner, repo string, oid domain.OID, size domain.Size, hashAlgo string) usecase.ResponseObject {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleUploadObject", ctx, baseURL, owner, repo, oid, size, hashAlgo)
	ret0, _ := ret[0].(usecase.ResponseObject)
	return ret0
}

// HandleUploadObject indicates an expected call of HandleUploadObject.
func (mr *MockUploadUseCaseMockRecorder) HandleUploadObject(ctx, baseURL, owner, repo, oid, size, hashAlgo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUploadObject", reflect.TypeOf((*MockUploadUseCase)(nil).HandleUploadObject), ctx, baseURL, owner, repo, oid, size, hashAlgo)
}
