// Code generated by MockGen. DO NOT EDIT.
// Source: download_usecase.go
//
// Generated by this command:
//
//	mockgen -source=download_usecase.go -destination=../../tests/usecase/mock_download_usecase.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/na2na-p/cargohold/internal/domain"
	usecase "github.com/na2na-p/cargohold/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockDownloadUseCase is a mock of DownloadUseCase interface.
type MockDownloadUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockDownloadUseCaseMockRecorder
	isgomock struct{}
}

// MockDownloadUseCaseMockRecorder is the mock recorder for MockDownloadUseCase.
type MockDownloadUseCaseMockRecorder struct {
	mock *MockDownloadUseCase
}

// NewMockDownloadUseCase creates a new mock instance.
func NewMockDownloadUseCase(ctrl *gomock.Controller) *MockDownloadUseCase {
	mock := &MockDownloadUseCase{ctrl: ctrl}
	mock.recorder = &MockDownloadUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDownloadUseCase) EXPECT() *MockDownloadUseCaseMockRecorder {
	return m.recorder
}

// HandleDownloadObject mocks base method.
func (m *MockDownloadUseCase) HandleDownloadObject(ctx context.Context, baseURL, owner, repo string, oid domain.OID, size domain.Size, authHeader string) usecase.ResponseObject {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleDownloadObject", ctx, baseURL, owner, repo, oid, size, authHeader)
	ret0, _ := ret[0].(usecase.ResponseObject)
	return ret0
}

// HandleDownloadObject indicates an expected call of HandleDownloadObject.
func (mr *MockDownloadUseCaseMockRecorder) HandleDownloadObject(ctx, baseURL, owner, repo, oid, size, authHeader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleDownloadObject", reflect.TypeOf((*MockDownloadUseCase)(nil).HandleDownloadObject), ctx, baseURL, owner, repo, oid, size, authHeader)
}
