// Code generated by MockGen. DO NOT EDIT.
// Source: session_auth_usecase.go
//
// Generated by this command:
//
//	mockgen -source=session_auth_usecase.go -destination=../../tests/usecase/mock_session_auth_usecase.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase
