// Code generated by MockGen. DO NOT EDIT.
// Source: external_interfaces.go
//
// Generated by this command:
//
//	mockgen -source=external_interfaces.go -destination=../../tests/usecase/mock_external_interfaces.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	io "io"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockCacheKeyGenerator is a mock of CacheKeyGenerator interface.
type MockCacheKeyGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockCacheKeyGeneratorMockRecorder
	isgomock struct{}
}

// MockCacheKeyGeneratorMockRecorder is the mock recorder for MockCacheKeyGenerator.
type MockCacheKeyGeneratorMockRecorder struct {
	mock *MockCacheKeyGenerator
}

// NewMockCacheKeyGenerator creates a new mock instance.
func NewMockCacheKeyGenerator(ctrl *gomock.Controller) *MockCacheKeyGenerator {
	mock := &MockCacheKeyGenerator{ctrl: ctrl}
	mock.recorder = &MockCacheKeyGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheKeyGenerator) EXPECT() *MockCacheKeyGeneratorMockRecorder {
	return m.recorder
}

// BatchUploadKey mocks base method.
func (m *MockCacheKeyGenerator) BatchUploadKey(oid string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUploadKey", oid)
	ret0, _ := ret[0].(string)
	return ret0
}

// BatchUploadKey indicates an expected call of BatchUploadKey.
func (mr *MockCacheKeyGeneratorMockRecorder) BatchUploadKey(oid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUploadKey", reflect.TypeOf((*MockCacheKeyGenerator)(nil).BatchUploadKey), oid)
}

// MetadataKey mocks base method.
func (m *MockCacheKeyGenerator) MetadataKey(oid string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MetadataKey", oid)
	ret0, _ := ret[0].(string)
	return ret0
}

// MetadataKey indicates an expected call of MetadataKey.
func (mr *MockCacheKeyGeneratorMockRecorder) MetadataKey(oid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MetadataKey", reflect.TypeOf((*MockCacheKeyGenerator)(nil).MetadataKey), oid)
}

// SessionKey mocks base method.
func (m *MockCacheKeyGenerator) SessionKey(sessionID string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionKey", sessionID)
	ret0, _ := ret[0].(string)
	return ret0
}

// SessionKey indicates an expected call of SessionKey.
func (mr *MockCacheKeyGeneratorMockRecorder) SessionKey(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionKey", reflect.TypeOf((*MockCacheKeyGenerator)(nil).SessionKey), sessionID)
}

// MockCacheConfig is a mock of CacheConfig interface.
type MockCacheConfig struct {
	ctrl     *gomock.Controller
	recorder *MockCacheConfigMockRecorder
	isgomock struct{}
}

// MockCacheConfigMockRecorder is the mock recorder for MockCacheConfig.
type MockCacheConfigMockRecorder struct {
	mock *MockCacheConfig
}

// NewMockCacheConfig creates a new mock instance.
func NewMockCacheConfig(ctrl *gomock.Controller) *MockCacheConfig {
	mock := &MockCacheConfig{ctrl: ctrl}
	mock.recorder = &MockCacheConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheConfig) EXPECT() *MockCacheConfigMockRecorder {
	return m.recorder
}

// MetadataTTL mocks base method.
func (m *MockCacheConfig) MetadataTTL() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MetadataTTL")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// MetadataTTL indicates an expected call of MetadataTTL.
func (mr *MockCacheConfigMockRecorder) MetadataTTL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MetadataTTL", reflect.TypeOf((*MockCacheConfig)(nil).MetadataTTL))
}

// MockCacheClient is a mock of CacheClient interface.
type MockCacheClient struct {
	ctrl     *gomock.Controller
	recorder *MockCacheClientMockRecorder
	isgomock struct{}
}

// MockCacheClientMockRecorder is the mock recorder for MockCacheClient.
type MockCacheClientMockRecorder struct {
	mock *MockCacheClient
}

// NewMockCacheClient creates a new mock instance.
func NewMockCacheClient(ctrl *gomock.Controller) *MockCacheClient {
	mock := &MockCacheClient{ctrl: ctrl}
	mock.recorder = &MockCacheClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheClient) EXPECT() *MockCacheClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockCacheClient) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCacheClientMockRecorder) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCacheClient)(nil).Delete), ctx, key)
}

// Exists mocks base method.
func (m *MockCacheClient) Exists(ctx context.Context, key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockCacheClientMockRecorder) Exists(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockCacheClient)(nil).Exists), ctx, key)
}

// GetJSON mocks base method.
func (m *MockCacheClient) GetJSON(ctx context.Context, key string, dest any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJSON", ctx, key, dest)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetJSON indicates an expected call of GetJSON.
func (mr *MockCacheClientMockRecorder) GetJSON(ctx, key, dest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJSON", reflect.TypeOf((*MockCacheClient)(nil).GetJSON), ctx, key, dest)
}

// Set mocks base method.
func (m *MockCacheClient) Set(ctx context.Context, key string, value any, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockCacheClientMockRecorder) Set(ctx, key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCacheClient)(nil).Set), ctx, key, value, ttl)
}

// SetJSON mocks base method.
func (m *MockCacheClient) SetJSON(ctx context.Context, key string, value any, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetJSON", ctx, key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetJSON indicates an expected call of SetJSON.
func (mr *MockCacheClientMockRecorder) SetJSON(ctx, key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetJSON", reflect.TypeOf((*MockCacheClient)(nil).SetJSON), ctx, key, value, ttl)
}

// MockStorageKeyGenerator is a mock of StorageKeyGenerator interface.
type MockStorageKeyGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockStorageKeyGeneratorMockRecorder
	isgomock struct{}
}

// MockStorageKeyGeneratorMockRecorder is the mock recorder for MockStorageKeyGenerator.
type MockStorageKeyGeneratorMockRecorder struct {
	mock *MockStorageKeyGenerator
}

// NewMockStorageKeyGenerator creates a new mock instance.
func NewMockStorageKeyGenerator(ctrl *gomock.Controller) *MockStorageKeyGenerator {
	mock := &MockStorageKeyGenerator{ctrl: ctrl}
	mock.recorder = &MockStorageKeyGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageKeyGenerator) EXPECT() *MockStorageKeyGeneratorMockRecorder {
	return m.recorder
}

// GenerateStorageKey mocks base method.
func (m *MockStorageKeyGenerator) GenerateStorageKey(oid, hashAlgo string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateStorageKey", oid, hashAlgo)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateStorageKey indicates an expected call of GenerateStorageKey.
func (mr *MockStorageKeyGeneratorMockRecorder) GenerateStorageKey(oid, hashAlgo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateStorageKey", reflect.TypeOf((*MockStorageKeyGenerator)(nil).GenerateStorageKey), oid, hashAlgo)
}

// MockS3Client is a mock of S3Client interface.
type MockS3Client struct {
	ctrl     *gomock.Controller
	recorder *MockS3ClientMockRecorder
	isgomock struct{}
}

// MockS3ClientMockRecorder is the mock recorder for MockS3Client.
type MockS3ClientMockRecorder struct {
	mock *MockS3Client
}

// NewMockS3Client creates a new mock instance.
func NewMockS3Client(ctrl *gomock.Controller) *MockS3Client {
	mock := &MockS3Client{ctrl: ctrl}
	mock.recorder = &MockS3ClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3Client) EXPECT() *MockS3ClientMockRecorder {
	return m.recorder
}

// GenerateGetURL mocks base method.
func (m *MockS3Client) GenerateGetURL(ctx context.Context, key string, ttl time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateGetURL", ctx, key, ttl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateGetURL indicates an expected call of GenerateGetURL.
func (mr *MockS3ClientMockRecorder) GenerateGetURL(ctx, key, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateGetURL", reflect.TypeOf((*MockS3Client)(nil).GenerateGetURL), ctx, key, ttl)
}

// GeneratePutURL mocks base method.
func (m *MockS3Client) GeneratePutURL(ctx context.Context, key string, ttl time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePutURL", ctx, key, ttl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GeneratePutURL indicates an expected call of GeneratePutURL.
func (mr *MockS3ClientMockRecorder) GeneratePutURL(ctx, key, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePutURL", reflect.TypeOf((*MockS3Client)(nil).GeneratePutURL), ctx, key, ttl)
}

// MockObjectStorage is a mock of ObjectStorage interface.
type MockObjectStorage struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStorageMockRecorder
	isgomock struct{}
}

// MockObjectStorageMockRecorder is the mock recorder for MockObjectStorage.
type MockObjectStorageMockRecorder struct {
	mock *MockObjectStorage
}

// NewMockObjectStorage creates a new mock instance.
func NewMockObjectStorage(ctrl *gomock.Controller) *MockObjectStorage {
	mock := &MockObjectStorage{ctrl: ctrl}
	mock.recorder = &MockObjectStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStorage) EXPECT() *MockObjectStorageMockRecorder {
	return m.recorder
}

// GetObject mocks base method.
func (m *MockObjectStorage) GetObject(ctx context.Context, key string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject", ctx, key)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockObjectStorageMockRecorder) GetObject(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockObjectStorage)(nil).GetObject), ctx, key)
}

// PutObject mocks base method.
func (m *MockObjectStorage) PutObject(ctx context.Context, key string, body io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutObject", ctx, key, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutObject indicates an expected call of PutObject.
func (mr *MockObjectStorageMockRecorder) PutObject(ctx, key, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockObjectStorage)(nil).PutObject), ctx, key, body)
}

// MockActionURLGenerator is a mock of ActionURLGenerator interface.
type MockActionURLGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockActionURLGeneratorMockRecorder
	isgomock struct{}
}

// MockActionURLGeneratorMockRecorder is the mock recorder for MockActionURLGenerator.
type MockActionURLGeneratorMockRecorder struct {
	mock *MockActionURLGenerator
}

// NewMockActionURLGenerator creates a new mock instance.
func NewMockActionURLGenerator(ctrl *gomock.Controller) *MockActionURLGenerator {
	mock := &MockActionURLGenerator{ctrl: ctrl}
	mock.recorder = &MockActionURLGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActionURLGenerator) EXPECT() *MockActionURLGeneratorMockRecorder {
	return m.recorder
}

// GenerateDownloadURL mocks base method.
func (m *MockActionURLGenerator) GenerateDownloadURL(baseURL, owner, repo, oid string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateDownloadURL", baseURL, owner, repo, oid)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateDownloadURL indicates an expected call of GenerateDownloadURL.
func (mr *MockActionURLGeneratorMockRecorder) GenerateDownloadURL(baseURL, owner, repo, oid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateDownloadURL", reflect.TypeOf((*MockActionURLGenerator)(nil).GenerateDownloadURL), baseURL, owner, repo, oid)
}

// GenerateUploadURL mocks base method.
func (m *MockActionURLGenerator) GenerateUploadURL(baseURL, owner, repo, oid string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateUploadURL", baseURL, owner, repo, oid)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateUploadURL indicates an expected call of GenerateUploadURL.
func (mr *MockActionURLGeneratorMockRecorder) GenerateUploadURL(baseURL, owner, repo, oid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateUploadURL", reflect.TypeOf((*MockActionURLGenerator)(nil).GenerateUploadURL), baseURL, owner, repo, oid)
}
