// Code generated by MockGen. DO NOT EDIT.
// Source: verify_usecase.go
//
// Generated by this command:
//
//	mockgen -source=verify_usecase.go -destination=../../tests/usecase/mock_verify_usecase.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVerifyUseCaseInterface is a mock of VerifyUseCaseInterface interface.
type MockVerifyUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockVerifyUseCaseInterfaceMockRecorder
	isgomock struct{}
}

// MockVerifyUseCaseInterfaceMockRecorder is the mock recorder for MockVerifyUseCaseInterface.
type MockVerifyUseCaseInterfaceMockRecorder struct {
	mock *MockVerifyUseCaseInterface
}

// NewMockVerifyUseCaseInterface creates a new mock instance.
func NewMockVerifyUseCaseInterface(ctrl *gomock.Controller) *MockVerifyUseCaseInterface {
	mock := &MockVerifyUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockVerifyUseCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerifyUseCaseInterface) EXPECT() *MockVerifyUseCaseInterfaceMockRecorder {
	return m.recorder
}

// VerifyUpload mocks base method.
func (m *MockVerifyUseCaseInterface) VerifyUpload(ctx context.Context, oid string, size int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyUpload", ctx, oid, size)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyUpload indicates an expected call of VerifyUpload.
func (mr *MockVerifyUseCaseInterfaceMockRecorder) VerifyUpload(ctx, oid, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyUpload", reflect.TypeOf((*MockVerifyUseCaseInterface)(nil).VerifyUpload), ctx, oid, size)
}
