// Code generated by MockGen. DO NOT EDIT.
// Source: github_oauth_interfaces.go
//
// Generated by this command:
//
//	mockgen -source=github_oauth_interfaces.go -destination=../../tests/usecase/mock_github_oauth_interfaces.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/na2na-p/cargohold/internal/domain"
	usecase "github.com/na2na-p/cargohold/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockGitHubOAuthProviderInterface is a mock of GitHubOAuthProviderInterface interface.
type MockGitHubOAuthProviderInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGitHubOAuthProviderInterfaceMockRecorder
	isgomock struct{}
}

// MockGitHubOAuthProviderInterfaceMockRecorder is the mock recorder for MockGitHubOAuthProviderInterface.
type MockGitHubOAuthProviderInterfaceMockRecorder struct {
	mock *MockGitHubOAuthProviderInterface
}

// NewMockGitHubOAuthProviderInterface creates a new mock instance.
func NewMockGitHubOAuthProviderInterface(ctrl *gomock.Controller) *MockGitHubOAuthProviderInterface {
	mock := &MockGitHubOAuthProviderInterface{ctrl: ctrl}
	mock.recorder = &MockGitHubOAuthProviderInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitHubOAuthProviderInterface) EXPECT() *MockGitHubOAuthProviderInterfaceMockRecorder {
	return m.recorder
}

// CanAccessRepository mocks base method.
func (m *MockGitHubOAuthProviderInterface) CanAccessRepository(ctx context.Context, token *usecase.OAuthTokenResult, repo *domain.RepositoryIdentifier) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanAccessRepository", ctx, token, repo)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanAccessRepository indicates an expected call of CanAccessRepository.
func (mr *MockGitHubOAuthProviderInterfaceMockRecorder) CanAccessRepository(ctx, token, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanAccessRepository", reflect.TypeOf((*MockGitHubOAuthProviderInterface)(nil).CanAccessRepository), ctx, token, repo)
}

// ExchangeCode mocks base method.
func (m *MockGitHubOAuthProviderInterface) ExchangeCode(ctx context.Context, code string) (*usecase.OAuthTokenResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeCode", ctx, code)
	ret0, _ := ret[0].(*usecase.OAuthTokenResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeCode indicates an expected call of ExchangeCode.
func (mr *MockGitHubOAuthProviderInterfaceMockRecorder) ExchangeCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeCode", reflect.TypeOf((*MockGitHubOAuthProviderInterface)(nil).ExchangeCode), ctx, code)
}

// GetAuthorizationURL mocks base method.
func (m *MockGitHubOAuthProviderInterface) GetAuthorizationURL(state string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorizationURL", state)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAuthorizationURL indicates an expected call of GetAuthorizationURL.
func (mr *MockGitHubOAuthProviderInterfaceMockRecorder) GetAuthorizationURL(state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorizationURL", reflect.TypeOf((*MockGitHubOAuthProviderInterface)(nil).GetAuthorizationURL), state)
}

// GetRepositoryPermissions mocks base method.
func (m *MockGitHubOAuthProviderInterface) GetRepositoryPermissions(ctx context.Context, token *usecase.OAuthTokenResult, repo *domain.RepositoryIdentifier) (domain.RepositoryPermissions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoryPermissions", ctx, token, repo)
	ret0, _ := ret[0].(domain.RepositoryPermissions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoryPermissions indicates an expected call of GetRepositoryPermissions.
func (mr *MockGitHubOAuthProviderInterfaceMockRecorder) GetRepositoryPermissions(ctx, token, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoryPermissions", reflect.TypeOf((*MockGitHubOAuthProviderInterface)(nil).GetRepositoryPermissions), ctx, token, repo)
}

// GetUserInfo mocks base method.
func (m *MockGitHubOAuthProviderInterface) GetUserInfo(ctx context.Context, token *usecase.OAuthTokenResult) (*usecase.GitHubUserResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfo", ctx, token)
	ret0, _ := ret[0].(*usecase.GitHubUserResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfo indicates an expected call of GetUserInfo.
func (mr *MockGitHubOAuthProviderInterfaceMockRecorder) GetUserInfo(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*MockGitHubOAuthProviderInterface)(nil).GetUserInfo), ctx, token)
}

// SetRedirectURI mocks base method.
func (m *MockGitHubOAuthProviderInterface) SetRedirectURI(redirectURI string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRedirectURI", redirectURI)
}

// SetRedirectURI indicates an expected call of SetRedirectURI.
func (mr *MockGitHubOAuthProviderInterfaceMockRecorder) SetRedirectURI(redirectURI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRedirectURI", reflect.TypeOf((*MockGitHubOAuthProviderInterface)(nil).SetRedirectURI), redirectURI)
}

// MockOAuthStateStoreInterface is a mock of OAuthStateStoreInterface interface.
type MockOAuthStateStoreInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthStateStoreInterfaceMockRecorder
	isgomock struct{}
}

// MockOAuthStateStoreInterfaceMockRecorder is the mock recorder for MockOAuthStateStoreInterface.
type MockOAuthStateStoreInterfaceMockRecorder struct {
	mock *MockOAuthStateStoreInterface
}

// NewMockOAuthStateStoreInterface creates a new mock instance.
func NewMockOAuthStateStoreInterface(ctrl *gomock.Controller) *MockOAuthStateStoreInterface {
	mock := &MockOAuthStateStoreInterface{ctrl: ctrl}
	mock.recorder = &MockOAuthStateStoreInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthStateStoreInterface) EXPECT() *MockOAuthStateStoreInterfaceMockRecorder {
	return m.recorder
}

// GetAndDeleteState mocks base method.
func (m *MockOAuthStateStoreInterface) GetAndDeleteState(ctx context.Context, state string) (*domain.OAuthState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAndDeleteState", ctx, state)
	ret0, _ := ret[0].(*domain.OAuthState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAndDeleteState indicates an expected call of GetAndDeleteState.
func (mr *MockOAuthStateStoreInterfaceMockRecorder) GetAndDeleteState(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAndDeleteState", reflect.TypeOf((*MockOAuthStateStoreInterface)(nil).GetAndDeleteState), ctx, state)
}

// SaveState mocks base method.
func (m *MockOAuthStateStoreInterface) SaveState(ctx context.Context, state string, data *domain.OAuthState, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveState", ctx, state, data, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveState indicates an expected call of SaveState.
func (mr *MockOAuthStateStoreInterfaceMockRecorder) SaveState(ctx, state, data, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveState", reflect.TypeOf((*MockOAuthStateStoreInterface)(nil).SaveState), ctx, state, data, ttl)
}

// MockSessionStoreInterface is a mock of SessionStoreInterface interface.
type MockSessionStoreInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSessionStoreInterfaceMockRecorder
	isgomock struct{}
}

// MockSessionStoreInterfaceMockRecorder is the mock recorder for MockSessionStoreInterface.
type MockSessionStoreInterfaceMockRecorder struct {
	mock *MockSessionStoreInterface
}

// NewMockSessionStoreInterface creates a new mock instance.
func NewMockSessionStoreInterface(ctrl *gomock.Controller) *MockSessionStoreInterface {
	mock := &MockSessionStoreInterface{ctrl: ctrl}
	mock.recorder = &MockSessionStoreInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionStoreInterface) EXPECT() *MockSessionStoreInterfaceMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockSessionStoreInterface) CreateSession(ctx context.Context, userInfo *domain.UserInfo, ttl time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, userInfo, ttl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockSessionStoreInterfaceMockRecorder) CreateSession(ctx, userInfo, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockSessionStoreInterface)(nil).CreateSession), ctx, userInfo, ttl)
}

// DeleteSession mocks base method.
func (m *MockSessionStoreInterface) DeleteSession(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockSessionStoreInterfaceMockRecorder) DeleteSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockSessionStoreInterface)(nil).DeleteSession), ctx, sessionID)
}

// GetSession mocks base method.
func (m *MockSessionStoreInterface) GetSession(ctx context.Context, sessionID string) (*domain.UserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, sessionID)
	ret0, _ := ret[0].(*domain.UserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockSessionStoreInterfaceMockRecorder) GetSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockSessionStoreInterface)(nil).GetSession), ctx, sessionID)
}
