// Code generated by MockGen. DO NOT EDIT.
// Source: proxy_upload_usecase.go
//
// Generated by this command:
//
//	mockgen -source=proxy_upload_usecase.go -destination=../../tests/usecase/mock_proxy_upload_usecase.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	io "io"
	reflect "reflect"

	domain "github.com/na2na-p/cargohold/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockProxyUploadUseCase is a mock of ProxyUploadUseCase interface.
type MockProxyUploadUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockProxyUploadUseCaseMockRecorder
	isgomock struct{}
}

// MockProxyUploadUseCaseMockRecorder is the mock recorder for MockProxyUploadUseCase.
type MockProxyUploadUseCaseMockRecorder struct {
	mock *MockProxyUploadUseCase
}

// NewMockProxyUploadUseCase creates a new mock instance.
func NewMockProxyUploadUseCase(ctrl *gomock.Controller) *MockProxyUploadUseCase {
	mock := &MockProxyUploadUseCase{ctrl: ctrl}
	mock.recorder = &MockProxyUploadUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProxyUploadUseCase) EXPECT() *MockProxyUploadUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockProxyUploadUseCase) Execute(ctx context.Context, owner, repo string, oid domain.OID, body io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, owner, repo, oid, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockProxyUploadUseCaseMockRecorder) Execute(ctx, owner, repo, oid, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockProxyUploadUseCase)(nil).Execute), ctx, owner, repo, oid, body)
}
