// Code generated by MockGen. DO NOT EDIT.
// Source: batch_download_usecase.go
//
// Generated by this command:
//
//	mockgen -source=batch_download_usecase.go -destination=../../tests/usecase/mock_batch_download_usecase.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	usecase "github.com/na2na-p/cargohold/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockBatchDownloadUseCase is a mock of BatchDownloadUseCase interface.
type MockBatchDownloadUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockBatchDownloadUseCaseMockRecorder
	isgomock struct{}
}

// MockBatchDownloadUseCaseMockRecorder is the mock recorder for MockBatchDownloadUseCase.
type MockBatchDownloadUseCaseMockRecorder struct {
	mock *MockBatchDownloadUseCase
}

// NewMockBatchDownloadUseCase creates a new mock instance.
func NewMockBatchDownloadUseCase(ctrl *gomock.Controller) *MockBatchDownloadUseCase {
	mock := &MockBatchDownloadUseCase{ctrl: ctrl}
	mock.recorder = &MockBatchDownloadUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatchDownloadUseCase) EXPECT() *MockBatchDownloadUseCaseMockRecorder {
	return m.recorder
}

// HandleBatchDownload mocks base method.
func (m *MockBatchDownloadUseCase) HandleBatchDownload(ctx context.Context, req usecase.BatchRequest) (usecase.BatchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleBatchDownload", ctx, req)
	ret0, _ := ret[0].(usecase.BatchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleBatchDownload indicates an expected call of HandleBatchDownload.
func (mr *MockBatchDownloadUseCaseMockRecorder) HandleBatchDownload(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleBatchDownload", reflect.TypeOf((*MockBatchDownloadUseCase)(nil).HandleBatchDownload), ctx, req)
}
