// Code generated by MockGen. DO NOT EDIT.
// Source: batch_upload_usecase.go
//
// Generated by this command:
//
//	mockgen -source=batch_upload_usecase.go -destination=../../tests/usecase/mock_batch_upload_usecase.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	usecase "github.com/na2na-p/cargohold/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockBatchUploadUseCase is a mock of BatchUploadUseCase interface.
type MockBatchUploadUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockBatchUploadUseCaseMockRecorder
	isgomock struct{}
}

// MockBatchUploadUseCaseMockRecorder is the mock recorder for MockBatchUploadUseCase.
type MockBatchUploadUseCaseMockRecorder struct {
	mock *MockBatchUploadUseCase
}

// NewMockBatchUploadUseCase creates a new mock instance.
func NewMockBatchUploadUseCase(ctrl *gomock.Controller) *MockBatchUploadUseCase {
	mock := &MockBatchUploadUseCase{ctrl: ctrl}
	mock.recorder = &MockBatchUploadUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatchUploadUseCase) EXPECT() *MockBatchUploadUseCaseMockRecorder {
	return m.recorder
}

// HandleBatchUpload mocks base method.
func (m *MockBatchUploadUseCase) HandleBatchUpload(ctx context.Context, baseURL, owner, repo string, req usecase.BatchRequest, authHeader string) (usecase.BatchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleBatchUpload", ctx, baseURL, owner, repo, req, authHeader)
	ret0, _ := ret[0].(usecase.BatchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleBatchUpload indicates an expected call of HandleBatchUpload.
func (mr *MockBatchUploadUseCaseMockRecorder) HandleBatchUpload(ctx, baseURL, owner, repo, req, authHeader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleBatchUpload", reflect.TypeOf((*MockBatchUploadUseCase)(nil).HandleBatchUpload), ctx, baseURL, owner, repo, req, authHeader)
}
