// Code generated by MockGen. DO NOT EDIT.
// Source: batch_usecase.go
//
// Generated by this command:
//
//	mockgen -source=batch_usecase.go -destination=../../tests/usecase/mock_batch_usecase.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase
