// Code generated by MockGen. DO NOT EDIT.
// Source: oidc_provider.go
//
// Generated by this command:
//
//	mockgen -source=oidc_provider.go -destination=../../tests/usecase/mock_oidc_provider.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/na2na-p/cargohold/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockOIDCProvider is a mock of OIDCProvider interface.
type MockOIDCProvider struct {
	ctrl     *gomock.Controller
	recorder *MockOIDCProviderMockRecorder
	isgomock struct{}
}

// MockOIDCProviderMockRecorder is the mock recorder for MockOIDCProvider.
type MockOIDCProviderMockRecorder struct {
	mock *MockOIDCProvider
}

// NewMockOIDCProvider creates a new mock instance.
func NewMockOIDCProvider(ctrl *gomock.Controller) *MockOIDCProvider {
	mock := &MockOIDCProvider{ctrl: ctrl}
	mock.recorder = &MockOIDCProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOIDCProvider) EXPECT() *MockOIDCProviderMockRecorder {
	return m.recorder
}

// ExchangeCode mocks base method.
func (m *MockOIDCProvider) ExchangeCode(ctx context.Context, code string) (*domain.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeCode", ctx, code)
	ret0, _ := ret[0].(*domain.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeCode indicates an expected call of ExchangeCode.
func (mr *MockOIDCProviderMockRecorder) ExchangeCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeCode", reflect.TypeOf((*MockOIDCProvider)(nil).ExchangeCode), ctx, code)
}

// GetAuthURL mocks base method.
func (m *MockOIDCProvider) GetAuthURL(ctx context.Context, state string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthURL", ctx, state)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthURL indicates an expected call of GetAuthURL.
func (mr *MockOIDCProviderMockRecorder) GetAuthURL(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthURL", reflect.TypeOf((*MockOIDCProvider)(nil).GetAuthURL), ctx, state)
}

// VerifyIDToken mocks base method.
func (m *MockOIDCProvider) VerifyIDToken(ctx context.Context, idToken string) (*domain.UserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyIDToken", ctx, idToken)
	ret0, _ := ret[0].(*domain.UserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyIDToken indicates an expected call of VerifyIDToken.
func (mr *MockOIDCProviderMockRecorder) VerifyIDToken(ctx, idToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyIDToken", reflect.TypeOf((*MockOIDCProvider)(nil).VerifyIDToken), ctx, idToken)
}
