// Code generated by MockGen. DO NOT EDIT.
// Source: token_exchanger.go
//
// Generated by this command:
//
//	mockgen -source=token_exchanger.go -destination=mock_token_exchanger_test.go -package=oidc
//

// Package oidc is a generated GoMock package.
package oidc

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTokenExchanger is a mock of TokenExchanger interface.
type MockTokenExchanger struct {
	ctrl     *gomock.Controller
	recorder *MockTokenExchangerMockRecorder
	isgomock struct{}
}

// MockTokenExchangerMockRecorder is the mock recorder for MockTokenExchanger.
type MockTokenExchangerMockRecorder struct {
	mock *MockTokenExchanger
}

// NewMockTokenExchanger creates a new mock instance.
func NewMockTokenExchanger(ctrl *gomock.Controller) *MockTokenExchanger {
	mock := &MockTokenExchanger{ctrl: ctrl}
	mock.recorder = &MockTokenExchangerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenExchanger) EXPECT() *MockTokenExchangerMockRecorder {
	return m.recorder
}

// ExchangeCode mocks base method.
func (m *MockTokenExchanger) ExchangeCode(ctx context.Context, code string) (*oauthToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeCode", ctx, code)
	ret0, _ := ret[0].(*oauthToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeCode indicates an expected call of ExchangeCode.
func (mr *MockTokenExchangerMockRecorder) ExchangeCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeCode", reflect.TypeOf((*MockTokenExchanger)(nil).ExchangeCode), ctx, code)
}

// GetAuthorizationURL mocks base method.
func (m *MockTokenExchanger) GetAuthorizationURL(state string, scopes []string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorizationURL", state, scopes)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAuthorizationURL indicates an expected call of GetAuthorizationURL.
func (mr *MockTokenExchangerMockRecorder) GetAuthorizationURL(state, scopes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorizationURL", reflect.TypeOf((*MockTokenExchanger)(nil).GetAuthorizationURL), state, scopes)
}
