// Code generated by MockGen. DO NOT EDIT.
// Source: github_oauth_provider_adapter.go
//
// Generated by this command:
//
//	mockgen -source=github_oauth_provider_adapter.go -destination=mock_github_oauth_provider_internal_test.go -package=oidc
//

// Package oidc is a generated GoMock package.
package oidc

import (
	context "context"
	reflect "reflect"

	domain "github.com/na2na-p/cargohold/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockGitHubOAuthProviderInternal is a mock of GitHubOAuthProviderInternal interface.
type MockGitHubOAuthProviderInternal struct {
	ctrl     *gomock.Controller
	recorder *MockGitHubOAuthProviderInternalMockRecorder
	isgomock struct{}
}

// MockGitHubOAuthProviderInternalMockRecorder is the mock recorder for MockGitHubOAuthProviderInternal.
type MockGitHubOAuthProviderInternalMockRecorder struct {
	mock *MockGitHubOAuthProviderInternal
}

// NewMockGitHubOAuthProviderInternal creates a new mock instance.
func NewMockGitHubOAuthProviderInternal(ctrl *gomock.Controller) *MockGitHubOAuthProviderInternal {
	mock := &MockGitHubOAuthProviderInternal{ctrl: ctrl}
	mock.recorder = &MockGitHubOAuthProviderInternalMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitHubOAuthProviderInternal) EXPECT() *MockGitHubOAuthProviderInternalMockRecorder {
	return m.recorder
}

// CanAccessRepository mocks base method.
func (m *MockGitHubOAuthProviderInternal) CanAccessRepository(ctx context.Context, token *oauthToken, repo *domain.RepositoryIdentifier) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanAccessRepository", ctx, token, repo)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanAccessRepository indicates an expected call of CanAccessRepository.
func (mr *MockGitHubOAuthProviderInternalMockRecorder) CanAccessRepository(ctx, token, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanAccessRepository", reflect.TypeOf((*MockGitHubOAuthProviderInternal)(nil).CanAccessRepository), ctx, token, repo)
}

// ExchangeCode mocks base method.
func (m *MockGitHubOAuthProviderInternal) ExchangeCode(ctx context.Context, code string) (*oauthToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeCode", ctx, code)
	ret0, _ := ret[0].(*oauthToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeCode indicates an expected call of ExchangeCode.
func (mr *MockGitHubOAuthProviderInternalMockRecorder) ExchangeCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeCode", reflect.TypeOf((*MockGitHubOAuthProviderInternal)(nil).ExchangeCode), ctx, code)
}

// GetAuthorizationURL mocks base method.
func (m *MockGitHubOAuthProviderInternal) GetAuthorizationURL(state string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorizationURL", state)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAuthorizationURL indicates an expected call of GetAuthorizationURL.
func (mr *MockGitHubOAuthProviderInternalMockRecorder) GetAuthorizationURL(state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorizationURL", reflect.TypeOf((*MockGitHubOAuthProviderInternal)(nil).GetAuthorizationURL), state)
}

// GetRepositoryPermissions mocks base method.
func (m *MockGitHubOAuthProviderInternal) GetRepositoryPermissions(ctx context.Context, token *oauthToken, repo *domain.RepositoryIdentifier) (domain.RepositoryPermissions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoryPermissions", ctx, token, repo)
	ret0, _ := ret[0].(domain.RepositoryPermissions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoryPermissions indicates an expected call of GetRepositoryPermissions.
func (mr *MockGitHubOAuthProviderInternalMockRecorder) GetRepositoryPermissions(ctx, token, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoryPermissions", reflect.TypeOf((*MockGitHubOAuthProviderInternal)(nil).GetRepositoryPermissions), ctx, token, repo)
}

// GetUserInfo mocks base method.
func (m *MockGitHubOAuthProviderInternal) GetUserInfo(ctx context.Context, token *oauthToken) (*gitHubUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfo", ctx, token)
	ret0, _ := ret[0].(*gitHubUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfo indicates an expected call of GetUserInfo.
func (mr *MockGitHubOAuthProviderInternalMockRecorder) GetUserInfo(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*MockGitHubOAuthProviderInternal)(nil).GetUserInfo), ctx, token)
}

// SetRedirectURI mocks base method.
func (m *MockGitHubOAuthProviderInternal) SetRedirectURI(redirectURI string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRedirectURI", redirectURI)
}

// SetRedirectURI indicates an expected call of SetRedirectURI.
func (mr *MockGitHubOAuthProviderInternalMockRecorder) SetRedirectURI(redirectURI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRedirectURI", reflect.TypeOf((*MockGitHubOAuthProviderInternal)(nil).SetRedirectURI), redirectURI)
}
