// Code generated by MockGen. DO NOT EDIT.
// Source: repository_checker.go
//
// Generated by this command:
//
//	mockgen -source=repository_checker.go -destination=mock_repository_checker_test.go -package=oidc
//

// Package oidc is a generated GoMock package.
package oidc

import (
	context "context"
	reflect "reflect"

	domain "github.com/na2na-p/cargohold/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRepositoryChecker is a mock of RepositoryChecker interface.
type MockRepositoryChecker struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryCheckerMockRecorder
	isgomock struct{}
}

// MockRepositoryCheckerMockRecorder is the mock recorder for MockRepositoryChecker.
type MockRepositoryCheckerMockRecorder struct {
	mock *MockRepositoryChecker
}

// NewMockRepositoryChecker creates a new mock instance.
func NewMockRepositoryChecker(ctrl *gomock.Controller) *MockRepositoryChecker {
	mock := &MockRepositoryChecker{ctrl: ctrl}
	mock.recorder = &MockRepositoryCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryChecker) EXPECT() *MockRepositoryCheckerMockRecorder {
	return m.recorder
}

// CanAccessRepository mocks base method.
func (m *MockRepositoryChecker) CanAccessRepository(ctx context.Context, token *oauthToken, repo *domain.RepositoryIdentifier) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanAccessRepository", ctx, token, repo)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanAccessRepository indicates an expected call of CanAccessRepository.
func (mr *MockRepositoryCheckerMockRecorder) CanAccessRepository(ctx, token, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanAccessRepository", reflect.TypeOf((*MockRepositoryChecker)(nil).CanAccessRepository), ctx, token, repo)
}
