// Code generated by MockGen. DO NOT EDIT.
// Source: auth_dispatcher.go
//
// Generated by this command:
//
//	mockgen -source=auth_dispatcher.go -destination=../../../tests/handler/middleware/mock_auth_dispatcher.go -package=middleware
//

// Package middleware is a generated GoMock package.
package middleware

import (
	context "context"
	reflect "reflect"

	domain "github.com/na2na-p/cargohold/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthUseCaseInterface is a mock of AuthUseCaseInterface interface.
type MockAuthUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthUseCaseInterfaceMockRecorder
	isgomock struct{}
}

// MockAuthUseCaseInterfaceMockRecorder is the mock recorder for MockAuthUseCaseInterface.
type MockAuthUseCaseInterfaceMockRecorder struct {
	mock *MockAuthUseCaseInterface
}

// NewMockAuthUseCaseInterface creates a new mock instance.
func NewMockAuthUseCaseInterface(ctrl *gomock.Controller) *MockAuthUseCaseInterface {
	mock := &MockAuthUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockAuthUseCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthUseCaseInterface) EXPECT() *MockAuthUseCaseInterfaceMockRecorder {
	return m.recorder
}

// AuthenticateGitHubOIDC mocks base method.
func (m *MockAuthUseCaseInterface) AuthenticateGitHubOIDC(ctx context.Context, token string) (*domain.UserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticateGitHubOIDC", ctx, token)
	ret0, _ := ret[0].(*domain.UserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthenticateGitHubOIDC indicates an expected call of AuthenticateGitHubOIDC.
func (mr *MockAuthUseCaseInterfaceMockRecorder) AuthenticateGitHubOIDC(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateGitHubOIDC", reflect.TypeOf((*MockAuthUseCaseInterface)(nil).AuthenticateGitHubOIDC), ctx, token)
}

// AuthenticateSession mocks base method.
func (m *MockAuthUseCaseInterface) AuthenticateSession(ctx context.Context, sessionID string) (*domain.UserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticateSession", ctx, sessionID)
	ret0, _ := ret[0].(*domain.UserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthenticateSession indicates an expected call of AuthenticateSession.
func (mr *MockAuthUseCaseInterfaceMockRecorder) AuthenticateSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateSession", reflect.TypeOf((*MockAuthUseCaseInterface)(nil).AuthenticateSession), ctx, sessionID)
}
