// Code generated by MockGen. DO NOT EDIT.
// Source: user_info_serializer.go
//
// Generated by this command:
//
//	mockgen -source=user_info_serializer.go -destination=../../../tests/infrastructure/redis/mock_user_info_serializer.go -package=redis
//

// Package redis is a generated GoMock package.
package redis

import (
	reflect "reflect"

	domain "github.com/na2na-p/cargohold/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUserInfoSerializer is a mock of UserInfoSerializer interface.
type MockUserInfoSerializer struct {
	ctrl     *gomock.Controller
	recorder *MockUserInfoSerializerMockRecorder
	isgomock struct{}
}

// MockUserInfoSerializerMockRecorder is the mock recorder for MockUserInfoSerializer.
type MockUserInfoSerializerMockRecorder struct {
	mock *MockUserInfoSerializer
}

// NewMockUserInfoSerializer creates a new mock instance.
func NewMockUserInfoSerializer(ctrl *gomock.Controller) *MockUserInfoSerializer {
	mock := &MockUserInfoSerializer{ctrl: ctrl}
	mock.recorder = &MockUserInfoSerializerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserInfoSerializer) EXPECT() *MockUserInfoSerializerMockRecorder {
	return m.recorder
}

// Deserialize mocks base method.
func (m *MockUserInfoSerializer) Deserialize(data []byte) (*domain.UserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deserialize", data)
	ret0, _ := ret[0].(*domain.UserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Deserialize indicates an expected call of Deserialize.
func (mr *MockUserInfoSerializerMockRecorder) Deserialize(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deserialize", reflect.TypeOf((*MockUserInfoSerializer)(nil).Deserialize), data)
}

// Serialize mocks base method.
func (m *MockUserInfoSerializer) Serialize(userInfo *domain.UserInfo) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Serialize", userInfo)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Serialize indicates an expected call of Serialize.
func (mr *MockUserInfoSerializerMockRecorder) Serialize(userInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Serialize", reflect.TypeOf((*MockUserInfoSerializer)(nil).Serialize), userInfo)
}

// MockGitHubUserInfoSerializer is a mock of GitHubUserInfoSerializer interface.
type MockGitHubUserInfoSerializer struct {
	ctrl     *gomock.Controller
	recorder *MockGitHubUserInfoSerializerMockRecorder
	isgomock struct{}
}

// MockGitHubUserInfoSerializerMockRecorder is the mock recorder for MockGitHubUserInfoSerializer.
type MockGitHubUserInfoSerializerMockRecorder struct {
	mock *MockGitHubUserInfoSerializer
}

// NewMockGitHubUserInfoSerializer creates a new mock instance.
func NewMockGitHubUserInfoSerializer(ctrl *gomock.Controller) *MockGitHubUserInfoSerializer {
	mock := &MockGitHubUserInfoSerializer{ctrl: ctrl}
	mock.recorder = &MockGitHubUserInfoSerializerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitHubUserInfoSerializer) EXPECT() *MockGitHubUserInfoSerializerMockRecorder {
	return m.recorder
}

// Deserialize mocks base method.
func (m *MockGitHubUserInfoSerializer) Deserialize(data []byte) (*domain.GitHubUserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deserialize", data)
	ret0, _ := ret[0].(*domain.GitHubUserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Deserialize indicates an expected call of Deserialize.
func (mr *MockGitHubUserInfoSerializerMockRecorder) Deserialize(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deserialize", reflect.TypeOf((*MockGitHubUserInfoSerializer)(nil).Deserialize), data)
}

// Serialize mocks base method.
func (m *MockGitHubUserInfoSerializer) Serialize(userInfo *domain.GitHubUserInfo) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Serialize", userInfo)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Serialize indicates an expected call of Serialize.
func (mr *MockGitHubUserInfoSerializerMockRecorder) Serialize(userInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Serialize", reflect.TypeOf((*MockGitHubUserInfoSerializer)(nil).Serialize), userInfo)
}
