// Code generated by MockGen. DO NOT EDIT.
// Source: batch_handler.go
//
// Generated by this command:
//
//	mockgen -source=batch_handler.go -destination=../../tests/handler/mock_batch_handler.go -package=handler
//

// Package handler is a generated GoMock package.
package handler

import (
	context "context"
	reflect "reflect"

	usecase "github.com/na2na-p/cargohold/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockBatchUseCaseInterface is a mock of BatchUseCaseInterface interface.
type MockBatchUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBatchUseCaseInterfaceMockRecorder
	isgomock struct{}
}

// MockBatchUseCaseInterfaceMockRecorder is the mock recorder for MockBatchUseCaseInterface.
type MockBatchUseCaseInterfaceMockRecorder struct {
	mock *MockBatchUseCaseInterface
}

// NewMockBatchUseCaseInterface creates a new mock instance.
func NewMockBatchUseCaseInterface(ctrl *gomock.Controller) *MockBatchUseCaseInterface {
	mock := &MockBatchUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockBatchUseCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatchUseCaseInterface) EXPECT() *MockBatchUseCaseInterfaceMockRecorder {
	return m.recorder
}

// HandleBatchRequest mocks base method.
func (m *MockBatchUseCaseInterface) HandleBatchRequest(ctx context.Context, req usecase.BatchRequest) (usecase.BatchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleBatchRequest", ctx, req)
	ret0, _ := ret[0].(usecase.BatchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleBatchRequest indicates an expected call of HandleBatchRequest.
func (mr *MockBatchUseCaseInterfaceMockRecorder) HandleBatchRequest(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleBatchRequest", reflect.TypeOf((*MockBatchUseCaseInterface)(nil).HandleBatchRequest), ctx, req)
}
