// Code generated by MockGen. DO NOT EDIT.
// Source: verify_handler.go
//
// Generated by this command:
//
//	mockgen -source=verify_handler.go -destination=../../tests/handler/mock_verify_handler.go -package=handler
//

// Package handler is a generated GoMock package.
package handler

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVerifyUseCase is a mock of VerifyUseCase interface.
type MockVerifyUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockVerifyUseCaseMockRecorder
	isgomock struct{}
}

// MockVerifyUseCaseMockRecorder is the mock recorder for MockVerifyUseCase.
type MockVerifyUseCaseMockRecorder struct {
	mock *MockVerifyUseCase
}

// NewMockVerifyUseCase creates a new mock instance.
func NewMockVerifyUseCase(ctrl *gomock.Controller) *MockVerifyUseCase {
	mock := &MockVerifyUseCase{ctrl: ctrl}
	mock.recorder = &MockVerifyUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerifyUseCase) EXPECT() *MockVerifyUseCaseMockRecorder {
	return m.recorder
}

// VerifyUpload mocks base method.
func (m *MockVerifyUseCase) VerifyUpload(ctx context.Context, oid string, size int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyUpload", ctx, oid, size)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyUpload indicates an expected call of VerifyUpload.
func (mr *MockVerifyUseCaseMockRecorder) VerifyUpload(ctx, oid, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyUpload", reflect.TypeOf((*MockVerifyUseCase)(nil).VerifyUpload), ctx, oid, size)
}
