// Code generated by MockGen. DO NOT EDIT.
// Source: readyz_handler.go
//
// Generated by this command:
//
//	mockgen -source=readyz_handler.go -destination=../../tests/handler/mock_readyz_handler.go -package=handler
//

// Package handler is a generated GoMock package.
package handler

import (
	context "context"
	reflect "reflect"

	usecase "github.com/na2na-p/cargohold/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockReadinessUseCaseInterface is a mock of ReadinessUseCaseInterface interface.
type MockReadinessUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockReadinessUseCaseInterfaceMockRecorder
	isgomock struct{}
}

// MockReadinessUseCaseInterfaceMockRecorder is the mock recorder for MockReadinessUseCaseInterface.
type MockReadinessUseCaseInterfaceMockRecorder struct {
	mock *MockReadinessUseCaseInterface
}

// NewMockReadinessUseCaseInterface creates a new mock instance.
func NewMockReadinessUseCaseInterface(ctrl *gomock.Controller) *MockReadinessUseCaseInterface {
	mock := &MockReadinessUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockReadinessUseCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadinessUseCaseInterface) EXPECT() *MockReadinessUseCaseInterfaceMockRecorder {
	return m.recorder
}

// ExecuteDetails mocks base method.
func (m *MockReadinessUseCaseInterface) ExecuteDetails(ctx context.Context) ([]usecase.HealthCheckResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteDetails", ctx)
	ret0, _ := ret[0].([]usecase.HealthCheckResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteDetails indicates an expected call of ExecuteDetails.
func (mr *MockReadinessUseCaseInterfaceMockRecorder) ExecuteDetails(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteDetails", reflect.TypeOf((*MockReadinessUseCaseInterface)(nil).ExecuteDetails), ctx)
}
