// Code generated by MockGen. DO NOT EDIT.
// Source: proxy_handler.go
//
// Generated by this command:
//
//	mockgen -source=proxy_handler.go -destination=../../tests/handler/mock_proxy_handler.go -package=handler
//

// Package handler is a generated GoMock package.
package handler

import (
	context "context"
	io "io"
	reflect "reflect"

	domain "github.com/na2na-p/cargohold/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockProxyUploadUseCase is a mock of ProxyUploadUseCase interface.
type MockProxyUploadUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockProxyUploadUseCaseMockRecorder
	isgomock struct{}
}

// MockProxyUploadUseCaseMockRecorder is the mock recorder for MockProxyUploadUseCase.
type MockProxyUploadUseCaseMockRecorder struct {
	mock *MockProxyUploadUseCase
}

// NewMockProxyUploadUseCase creates a new mock instance.
func NewMockProxyUploadUseCase(ctrl *gomock.Controller) *MockProxyUploadUseCase {
	mock := &MockProxyUploadUseCase{ctrl: ctrl}
	mock.recorder = &MockProxyUploadUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProxyUploadUseCase) EXPECT() *MockProxyUploadUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockProxyUploadUseCase) Execute(ctx context.Context, owner, repo string, oid domain.OID, body io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, owner, repo, oid, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockProxyUploadUseCaseMockRecorder) Execute(ctx, owner, repo, oid, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockProxyUploadUseCase)(nil).Execute), ctx, owner, repo, oid, body)
}

// MockProxyDownloadUseCase is a mock of ProxyDownloadUseCase interface.
type MockProxyDownloadUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockProxyDownloadUseCaseMockRecorder
	isgomock struct{}
}

// MockProxyDownloadUseCaseMockRecorder is the mock recorder for MockProxyDownloadUseCase.
type MockProxyDownloadUseCaseMockRecorder struct {
	mock *MockProxyDownloadUseCase
}

// NewMockProxyDownloadUseCase creates a new mock instance.
func NewMockProxyDownloadUseCase(ctrl *gomock.Controller) *MockProxyDownloadUseCase {
	mock := &MockProxyDownloadUseCase{ctrl: ctrl}
	mock.recorder = &MockProxyDownloadUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProxyDownloadUseCase) EXPECT() *MockProxyDownloadUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockProxyDownloadUseCase) Execute(ctx context.Context, owner, repo string, oid domain.OID) (io.ReadCloser, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, owner, repo, oid)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Execute indicates an expected call of Execute.
func (mr *MockProxyDownloadUseCaseMockRecorder) Execute(ctx, owner, repo, oid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockProxyDownloadUseCase)(nil).Execute), ctx, owner, repo, oid)
}
