// Code generated by MockGen. DO NOT EDIT.
// Source: user_info_provider.go
//
// Generated by this command:
//
//	mockgen -source=user_info_provider.go -destination=../../../tests/infrastructure/oidc/mock_user_info_provider.go -package=oidc
//

// Package oidc is a generated GoMock package.
package oidc

import (
	context "context"
	reflect "reflect"

	oidc "github.com/na2na-p/cargohold/internal/infrastructure/oidc"
	gomock "go.uber.org/mock/gomock"
)

// MockUserInfoProvider is a mock of UserInfoProvider interface.
type MockUserInfoProvider struct {
	ctrl     *gomock.Controller
	recorder *MockUserInfoProviderMockRecorder
	isgomock struct{}
}

// MockUserInfoProviderMockRecorder is the mock recorder for MockUserInfoProvider.
type MockUserInfoProviderMockRecorder struct {
	mock *MockUserInfoProvider
}

// NewMockUserInfoProvider creates a new mock instance.
func NewMockUserInfoProvider(ctrl *gomock.Controller) *MockUserInfoProvider {
	mock := &MockUserInfoProvider{ctrl: ctrl}
	mock.recorder = &MockUserInfoProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserInfoProvider) EXPECT() *MockUserInfoProviderMockRecorder {
	return m.recorder
}

// GetUserInfo mocks base method.
func (m *MockUserInfoProvider) GetUserInfo(ctx context.Context, token *oidc.OAuthToken) (*oidc.GitHubUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfo", ctx, token)
	ret0, _ := ret[0].(*oidc.GitHubUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfo indicates an expected call of GetUserInfo.
func (mr *MockUserInfoProviderMockRecorder) GetUserInfo(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*MockUserInfoProvider)(nil).GetUserInfo), ctx, token)
}
